### ISSUE TITLE
Predicting input nii files?

### ISSUE THREAD

**Issue by dscarmo** [abhi4ssj/quickNAT_pytorch#16]
Hello,

I can't seen to figure out how to run your code in, nift input files.

I was looking for something simple such as python3 run.py --in path/to/file.

Thank you!

**Comment by abhi4ssj** [comment]
Hi,
Please check the recently pushed upgrades. 

One important thing to do before deployment is to run 
```
mri_convert --conform <input_volume> <out_volume>
```
using FreeSurfer to standardize the input required for QuickNAT.

**Comment by abhi4ssj** [comment]
Closed due to inactivity. Feel free to open the issue if the problem persists.

**Comment by dscarmo** [comment]
Hello! Sorry for the delay on a response. I can't reopen the issue, probabyl because a repo member closed it?

I did install the requirements.txt packages and setup my settings_eval file correctly, and i got that error:


> python3 run.py --mode=eval_bulk
> **Starting evaluation**
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'quicknat.QuickNat' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.activation.PReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'nn_common_modules.modules.DecoderBlock' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> Traceback (most recent call last):
>   File "run.py", line 168, in <module>
>     evaluate_bulk(net_params, settings_eval['EVAL_BULK'])
>   File "run.py", line 137, in evaluate_bulk
>     mc_samples)
>   File "/home/diedre/git/quickNAT_pytorch/utils/evaluator.py", line 239, in evaluate
>     model.load_state_dict(torch.load(coronal_model_path))
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 751, in load_state_dict
>     state_dict = state_dict.copy()
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 539, in __getattr__
>     type(self).__name__, name))
> AttributeError: 'QuickNat' object has no attribute 'copy'
> 

Seems to be a problem on unpacking the saved weights, maybe new code is not compatible with the saved weights?

**Comment by abhi4ssj** [comment]
Hi,

I made some changes to the code. It should work out now. Although the warnings still persists. Let me know if it works out for you

Best
Abhijit

**Comment by dscarmo** [comment]
Thanks for the quick response!

Now i get this:

> **Starting evaluation**
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'quicknat.QuickNat' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.activation.PReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'nn_common_modules.modules.DecoderBlock' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> Evaluating now...
> Traceback (most recent call last):
>   File "run.py", line 168, in <module>
>     evaluate_bulk(net_params, settings_eval['EVAL_BULK'])
>   File "run.py", line 137, in evaluate_bulk
>     mc_samples)
>   File "/home/diedre/git/quickNAT_pytorch/utils/evaluator.py", line 264, in evaluate
>     device)
>   File "/home/diedre/git/quickNAT_pytorch/utils/evaluator.py", line 169, in _segment_vol
>     out = model(batch_x)
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/diedre/git/quickNAT_pytorch/quicknat.py", line 49, in forward
>     e1, out1, ind1 = self.encode1.forward(input)
>   File "/usr/local/lib/python3.6/dist-packages/nn_common_modules/modules.py", line 148, in forward
>     out_block = super(EncoderBlock, self).forward(input)
>   File "/usr/local/lib/python3.6/dist-packages/nn_common_modules/modules.py", line 99, in forward
>     o3 = self.conv1(o2)
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 331, in forward
>     if self.padding_mode == 'circular':
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 539, in __getattr__
>     type(self).__name__, name))
> AttributeError: 'Conv2d' object has no attribute 'padding_mode'
>

**Comment by abhi4ssj** [comment]
This is strange. Seems to work for me. What is your pytorch and CUDA version? I saw its not working on CUDA 10.1, but working on CUDA 9

**Comment by dscarmo** [comment]
CUDA 9 and pytorch 1.1.0

I ll try in another computer with newer pytorch and cuda 10.0.

**Comment by abhi4ssj** [comment]
I tried on a new computer and this worked out for me:
1. First I installed the requirements
2. Next I manually installed pytorch (version 1.3, ubuntu, anaconda, cuda 9.2)

Maybe try the similar sequence in a separate virtual environment

**Comment by dscarmo** [comment]
I updated to pytorch 1.3 and Cuda 10.2

Now i got that error:

> Evaluating now...
> Traceback (most recent call last):
>   File "run.py", line 168, in <module>
>     evaluate_bulk(net_params, settings_eval['EVAL_BULK'])
>   File "run.py", line 137, in evaluate_bulk
>     mc_samples)
>   File "/home/diedre/git/quickNAT_pytorch/utils/evaluator.py", line 264, in evaluate
>     device)
>   File "/home/diedre/git/quickNAT_pytorch/utils/evaluator.py", line 169, in _segment_vol
>     out = model(batch_x)
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/diedre/git/quickNAT_pytorch/quicknat.py", line 57, in forward
>     d3 = self.decode1.forward(d4, out3, ind3)
>   File "/usr/local/lib/python3.6/dist-packages/nn_common_modules/modules.py", line 201, in forward
>     concat = torch.cat((out_block, unpool), dim=1)
> RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 44 and 45 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71

Which is probably related to not performing mri_convert  (i wanted to see the effect).
Problem is, when i try to do mri_convert, seems like my nift files don't have enough orientation information in them, and mri_convert fails:

> niiRead(): NIFTI_UNITS_UNKNOWN, assuming mm
> WARNING: neither NIfTI-1 qform or sform are valid
> WARNING: your volume will probably be incorrectly oriented
> TR=0.00, TE=0.00, TI=0.00, flip angle=0.00
> WARNING: it does not appear that there was sufficient information
> in the input to assign orientation to the volume... 
> i_ras = (-1, 0, 0)
> j_ras = (0, 1, 0)
> k_ras = (0, 0, 1)
> changing data type from float to uchar (noscale = 0)...
> MRIchangeType: Building histogram 
> Reslicing using trilinear interpolation 
> MRIresample(): WARNING: ras_good_flag is not set, changing orientation
> to default.
> MRIresample(): source volume orientation is unknown
> No such file or directory

What kind of pre-processing can i do manually do replace mri_convert?

**Comment by abhi4ssj** [comment]
Hi,

I would recommend reconverting the nifti files from Dicom files maintaining the header information. Unfortunately I haven't used any other alternative versions of mri_convert.

**Comment by dscarmo** [comment]
Hi, i managed to get the original DICOM files and used them for mri_convert.

Thanks for the help!
About versioning, i could make it work in two different computes with torch 1.3 and cuda 10.2.

Thanks for the help, and nice work! Predictions seem to be very good.
